### ISSUE TITLE
Невозможно обратиться к свойству объекта как к функции

### ISSUE THREAD

**Issue by SergGrebnev** [SergGrebnev/JS_Web_05_Puppeteer_2_Cucumber#1]
В файле commands.js определено несколько функций. Не могу из одной функции вызвать другую.
this. использую, контекст не теряется, пробовал переходить на стрелочные функции.
Вопрос: как вызвать функцию из другой функции в файле commands.js (в какую сторону копать)?

Вызываю первую функцию:
https://github.com/SergGrebnev/JS_Web_05_Puppeteer_2_Cucumber/blob/ff0688f6a7809292c53072ad4d65a57264932166/net.test.js#L33

Из первой функции вызываю вторую:
https://github.com/SergGrebnev/JS_Web_05_Puppeteer_2_Cucumber/blob/ff0688f6a7809292c53072ad4d65a57264932166/lib/commands.js#L32

Ошибка: TypeError: this.searchAllElements is not a function
![image](https://github.com/user-attachments/assets/7e5a5927-2a47-4a52-b933-f4e0ae942c2f)

Если не использовать вызов функции из функции, а весь код поместить в одну функцию, то работает без ошибок
![image](https://github.com/user-attachments/assets/08d3ad3d-607f-493a-823a-c108385eadd0)

**Comment by korytoff** [comment]
Добрый вечер, Сергей. Вам тут скорее всего не нужен контекст this и достаточно вызывать одну функцию из другой напрямую.

Проще всего это сделать разделив объявления функций и дальнейший экспорт через `module.exports = {}`. Так же, это будет удобно т.к. `module.exports = {}` это старый подход к  (CommonJS Modulde) по работе с модулями в NodeJS и вам будет проще поддерживать код и переписывать код, когда у вас будут отдельно функции, а отдельно вспомогательный код для импорта/экспорта.

Попробуйте вот так

```JavaScript

// Объявляем и описываем все функции

// Поиск всех элементов странице по селектору
async function searchAllElements(page, selector) {
  try {
    await page.waitForSelector(selector);
    return await page.$$(selector);
  } catch (error) {
    throw new Error(`No elements found for selector: ${selector}`);
  }
}

//Выбор одного элемента из найденных на странице по порядковому номеру
async function selectOneElement(page, selector, number) {
  try {
    const elements = searchAllElements(page, selector); //массив элементов найденных по селектору
    return await elements[number];
  } catch (error) {
    throw new Error(`Element number ${number} not selected`);
  }
}

// ...

// Экспортируем нужные
module.exports = {
  searchAllElements,
  selectOneElement,
  selectRandomElement,
  // ...
}
```

**Comment by SergGrebnev** [comment]
Спасибо. Теперь всё работает.
